
---

#- hosts: LoadBalancer 
#  become: yes
  #become_user: root
#  roles:
#    - LoadBalancer-playbook

#- hosts: DNS_server
#  become: yes
#  roles:
#    - Bind-Playbook  

- hosts: all-nodes
  roles:
    - rke2-install-Playbook 
