- name: Get latest kubectl version
  when: ansible_host == '172.20.10.14'
  uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: version

- name: Download the latest kubectl release
  when: ansible_host == '172.20.10.14'
  uri:
    url: https://dl.k8s.io/release/{{ version.content }}/bin/linux/arm/kubectl
    dest: /home/{{ ansible_user }}
  register: kubectl

- name: Move kubectl and change permissions
  when: ansible_host == '172.20.10.14'
  file:
    src: "{{ kubectl.path }}"
    dest: /usr/local/bin/kubectl
    owner: root
    group: root
    mode: "755"
